# Generated by Django 4.2.7 on 2023-11-28 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='CarPrice',
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rental_api.cartype'),
            preserve_default=False,
        ),
    ]
