# Generated by Django 4.2.7 on 2023-11-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0003_alter_car_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartype',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
