# Generated by Django 4.2.7 on 2023-11-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0004_alter_cartype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
