# Generated by Django 4.2.7 on 2023-11-28 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental_api', '0005_rental_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='remoote_id',
        ),
        migrations.AddField(
            model_name='rental',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
