# Generated by Django 4.2.7 on 2023-11-29 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0006_remove_rental_remoote_id_rental_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
