# Generated by Django 4.2.7 on 2023-11-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0007_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
