# Generated by Django 4.2.7 on 2023-12-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0008_car_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
