# Generated by Django 4.2.7 on 2023-12-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0014_iha_remove_wallet_user_remove_rental_car_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name_plural': 'iletişim'},
        ),
    ]
