# Generated by Django 4.2.7 on 2023-12-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0015_alter_contactmessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Özel Nesne', 'verbose_name_plural': 'Özel Nesneler'},
        ),
    ]
