# Generated by Django 4.2.7 on 2023-12-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0016_alter_contactmessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterField(
            model_name='iha',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
