# Generated by Django 4.2.7 on 2023-12-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0017_alter_contactmessage_options_alter_iha_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iha',
            old_name='make',
            new_name='brand',
        ),
    ]
