# Generated by Django 4.2.7 on 2023-12-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0018_rename_make_iha_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iha',
            name='is_active',
        ),
    ]
