# Generated by Django 4.2.7 on 2023-12-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0019_remove_iha_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha',
            name='iha_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='melih', to='rental_api.ihatype'),
        ),
    ]
