# Generated by Django 4.2.7 on 2023-12-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0023_iha_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iha',
            name='is_active',
        ),
    ]
