# Generated by Django 4.2.7 on 2023-12-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0025_specialoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='iha',
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
