# Generated by Django 4.2.7 on 2023-12-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0026_remove_specialoffer_iha_specialoffer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
