# Generated by Django 4.2.7 on 2023-12-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0027_alter_specialoffer_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialOffer',
        ),
    ]
